# Generated by Django 6.0.4 on 2026-04-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_highlight',
            field=models.BooleanField(default=False),
        ),
    ]
