# Generated by Django 6.0.4 on 2026-04-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_video', '0003_alter_video_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
